/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentregistrationapp;

import java.awt.BorderLayout;
import javax.swing.*;

/**
 *
 * @author miller
 */
public class Mockup extends javax.swing.JFrame {

    private DB_Manager db;
    private JFrame frame;
    
    protected StudentMenu studentMenu;
    protected StudentCharts studentCharts;

    /**
     * Creates new form Mockup
     */
    public Mockup() {
        initComponents();
    }

    private void initialize() {
        // initializes the database and application with data
        db = new DB_Manager();
        db.readXMLFile();
        
        // creates instances of classes used
        frame = new JFrame("Student Registration");
        studentMenu = new StudentMenu(this);
        studentCharts = new StudentCharts(this);
        
        // displays the frame
        frame.setLayout(new BorderLayout());
        frame.add(studentMenu, BorderLayout.NORTH);
        frame.add(studentCharts, BorderLayout.SOUTH);
        frame.setSize(975, 600);   //change size to adjust all panels
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        
        studentMenu.updateUserInterface();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Mockup myApp = new Mockup();
        myApp.initialize();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
