/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentregistration;

import java.util.*;
import javax.swing.*;

/**
 *
 * @author miller
 */
public class StudentMenu extends javax.swing.JPanel {

    private Mockup myGUI;
    private StudentCharts studentCharts;
    private DefaultListModel jListModel = new DefaultListModel();

    protected DB_Manager db = new DB_Manager();
    protected ArrayList<StudentRecord> studentRecordData;

    // constructor
    public StudentMenu(Mockup mockup) {
        myGUI = mockup;
        studentRecordData = new ArrayList<>(Arrays.asList(db.queryRecords()));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        backupBtn = new javax.swing.JButton();
        firstNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        degreeStatusComboBox = new javax.swing.JComboBox<>();
        majorComboBox = new javax.swing.JComboBox<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Failed to input from database" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        backupBtn.setText("Backup");
        backupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Degree Status:");

        jLabel4.setText("Major:");

        degreeStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "full-time", "part-time", "non-degree", "provisional" }));

        majorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Business", "IST", "Nursing", "HDFS" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(majorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(degreeStatusComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backupBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(addBtn))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(deleteBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(degreeStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backupBtn))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(majorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void updateUserInterface() {
        // I did not want to query the database again but it seems to be one
        // of the only ways which works and also the easiest with how it is 
        // already set up... :/
        studentRecordData = new ArrayList<>(Arrays.asList(db.queryRecords()));
        // updates the jList
        jListModel.clear();
        // updates the model
        for (StudentRecord studentRecord : studentRecordData) {
            jListModel.addElement(studentRecord.toString());
        }
        // sets the jList to use the model
        jList1.setModel(jListModel);
        
        // updates the charts
        studentCharts = myGUI.studentCharts;
        studentCharts.createPieChart();
        studentCharts.createBarChart();
        
        resetTextFields();
    }

    private void resetTextFields() {
        firstNameTextField.setText("");
        lastNameTextField.setText("");
    }

    private boolean doesRecordExist(final StudentRecord studentRecord) {
        boolean result = false;
        if (jListModel.contains(studentRecord.toString())) {
            result = true;
        } else {
            JOptionPane.showMessageDialog(null, "Record does not exist", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        return result;
    }

    private boolean validateInput() {
        boolean result = false;
        if (firstNameTextField.getText().equals("")
                || lastNameTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter both a first and last name", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            result = true;
        }
        return result;
    }

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (validateInput()) {
            // creates a student record object
            StudentRecord studentRecord = new StudentRecord(firstNameTextField.getText(), lastNameTextField.getText(),
                    degreeStatusComboBox.getSelectedItem().toString(), majorComboBox.getSelectedItem().toString());
            // inserts StudentRecord into the database
            db.insertRecord(studentRecord);
            // add the new record to the jList directly, much faster than
            // running a new query to populate the jList
//            jListModel.addElement(studentRecord.toString());
            // adds element to the ArrayList of studentRecords and update chart
//            studentRecordData.add(studentRecord);
            updateUserInterface();
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // creates a student record object
        StudentRecord studentRecord = new StudentRecord(firstNameTextField.getText(), lastNameTextField.getText(),
                degreeStatusComboBox.getSelectedItem().toString(), majorComboBox.getSelectedItem().toString());
        if (validateInput() && doesRecordExist(studentRecord)) {
            // deletes StudentRecord in the database
            db.deleteRecord(studentRecord);
            // removes the new record from the jList
//            jListModel.removeElement(studentRecord.toString());
            // deletes element from the ArrayList of studentRecords and update chart
//            studentRecordData.remove(studentRecord);
            updateUserInterface();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void backupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupBtnActionPerformed
        db.writeXMLFile();
    }//GEN-LAST:event_backupBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backupBtn;
    private javax.swing.JComboBox<String> degreeStatusComboBox;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JComboBox<String> majorComboBox;
    // End of variables declaration//GEN-END:variables
}
