/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentregistration;

import java.util.*;
import javax.swing.*;

/**
 *
 * @author miller
 */
public class StudentMenu extends javax.swing.JPanel {

    private final Mockup myGUI;
    private StudentCharts studentCharts;
    private final DefaultListModel jListModel = new DefaultListModel();
    
    protected DB_Manager db = new DB_Manager();
    protected ArrayList<StudentRecord> studentRecordData;

    // constructor
    public StudentMenu(Mockup mockup) {
        myGUI = mockup;
        studentRecordData = new ArrayList<>(Arrays.asList(db.queryRecords()));
        initComponents();
        updateList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        backupBtn = new javax.swing.JButton();
        firstNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        degreeStatusTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        majorTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        displayBarChartBtn = new javax.swing.JButton();
        displayPieChartBtn = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Failed to input from database" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        backupBtn.setText("Backup");
        backupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backupBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Degree Status:");

        jLabel4.setText("Major:");

        displayBarChartBtn.setText("Display Bar Chart");
        displayBarChartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBarChartBtnActionPerformed(evt);
            }
        });

        displayPieChartBtn.setText("Display Pie Chart");
        displayPieChartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayPieChartBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(degreeStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(displayBarChartBtn)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(majorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backupBtn)
                                    .addComponent(deleteBtn))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(displayPieChartBtn)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(addBtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(deleteBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(degreeStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(7, 7, 7)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(majorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(backupBtn))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displayPieChartBtn)
                            .addComponent(displayBarChartBtn))
                        .addGap(31, 31, 31))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void updateList() {
        jListModel.clear();
        // updates the model
        for (StudentRecord studentRecord : studentRecordData) {
            jListModel.addElement(studentRecord.toString());
        }
        // sets the jList to use the model
        jList1.setModel(jListModel);
    }

    private void resetTextFields() {
        firstNameTextField.setText("");
        lastNameTextField.setText("");
        degreeStatusTextField.setText("");
        majorTextField.setText("");
    }

    private boolean doesRecordExist(StudentRecord studentRecord) {
        boolean result = false;
        if (jListModel.contains(studentRecord.toString())) {
            result = true;
        } else {
            JOptionPane.showMessageDialog(null, "Record does not exist", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
        return result;
    }

    private boolean validateInput() {
        boolean result = false;
        if (firstNameTextField.getText().equals("")
                || lastNameTextField.getText().equals("")
                || degreeStatusTextField.getText().equals("")
                || majorTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter input for all fields", "Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            result = true;
        }
        return result;
    }

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        if (validateInput()) {
            // creates a new student record object
            StudentRecord studentRecord = new StudentRecord(firstNameTextField.getText(), lastNameTextField.getText(),
                    degreeStatusTextField.getText(), majorTextField.getText());
            // inserts StudentRecord into the database
            db.insertRecord(studentRecord);
            // add the new record to the jList directly, much faster than
            // running a new query to populate the jList
            jListModel.addElement(studentRecord.toString());
            // adds element to the ArrayList of studentRecords and update chart
            studentRecordData.add(studentRecord);
            resetTextFields();
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // creates a new student record object
        StudentRecord studentRecord = new StudentRecord(firstNameTextField.getText(), lastNameTextField.getText(),
                degreeStatusTextField.getText(), majorTextField.getText());
        if (validateInput() && doesRecordExist(studentRecord)) {
            // deletes StudentRecord into the database
            db.deleteRecord(studentRecord);
            // removes the new record from the jList
            jListModel.removeElement(studentRecord.toString());
            // deletes element from the ArrayList of studentRecords and update chart
            studentRecordData.remove(studentRecord);
            resetTextFields();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void backupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backupBtnActionPerformed
        db.writeXMLFile();
    }//GEN-LAST:event_backupBtnActionPerformed

    private void displayBarChartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBarChartBtnActionPerformed
        studentCharts = myGUI.studentCharts;
        // if the chart is not open
        if (studentCharts.barChartFrame == null || !studentCharts.barChartFrame.isVisible()) {
            studentCharts.createBarChart();
        } else { // if the chart is already open
            studentCharts.barChartFrame.dispose();
            studentCharts.createBarChart();
        }
    }//GEN-LAST:event_displayBarChartBtnActionPerformed

    private void displayPieChartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayPieChartBtnActionPerformed
        studentCharts = myGUI.studentCharts;
        // if the chart is not open
        if (studentCharts.pieChartFrame == null || !studentCharts.pieChartFrame.isVisible()) {
            studentCharts.createPieChart();  
        } else { // if the chart is already open
            studentCharts.pieChartFrame.dispose();
            studentCharts.createPieChart();
        }
    }//GEN-LAST:event_displayPieChartBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backupBtn;
    private javax.swing.JTextField degreeStatusTextField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBarChartBtn;
    private javax.swing.JButton displayPieChartBtn;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JTextField majorTextField;
    // End of variables declaration//GEN-END:variables
}
