/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentregistration;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.util.Locale;
import javax.swing.JPanel;
import org.jfree.chart.*;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author miller
 */
public class StudentCharts extends javax.swing.JPanel {

    private final StudentMenu studentMenu;
    private Mockup myGUI;
    
    protected ChartPanel barChartPanel;
    protected ChartPanel pieChartPanel;

    // constructor
    public StudentCharts(Mockup mockup) {
        myGUI = mockup;
        studentMenu = mockup.studentMenu;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 322, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * displays the total number of students in each degree status category
     */
    protected void createBarChart() {
        System.out.println("createBarChart() called");
        
        // fill the chart with data
        DefaultCategoryDataset barchartDataset = new DefaultCategoryDataset();
        barchartDataset.setValue(countDegreeStatusOccurences("full-time"), "", "full-time");
        barchartDataset.setValue(countDegreeStatusOccurences("part-time"), "", "part-time");
        barchartDataset.setValue(countDegreeStatusOccurences("non-degree"), "", "non-degree");
        barchartDataset.setValue(countDegreeStatusOccurences("provisional"), "", "provisional");
        
        JFreeChart barChart = ChartFactory.createBarChart("Student Degree Status",
                "Degree Status", "Number of Students", barchartDataset,
                PlotOrientation.VERTICAL, false, false, false);

        CategoryPlot barChartCatPlot = barChart.getCategoryPlot();
        barChartCatPlot.setRangeGridlinePaint(Color.BLACK);
      
        barChartPanel = new ChartPanel(barChart);
        barChartPanel.setPreferredSize(new Dimension(450,300));
        
        this.jPanel1 = myGUI.studentCharts.jPanel1;
        jPanel1.setLayout(new BorderLayout());
        jPanel1.add(barChartPanel, BorderLayout.WEST);
        jPanel1.validate();
    }

    protected void createPieChart() {
        System.out.println("createPieChart() called");
        
        // fill the chart with data
        DefaultPieDataset pieChartDataset = new DefaultPieDataset();
        pieChartDataset.setValue("IST", countMajorOccurences("IST"));
        pieChartDataset.setValue("Business", countMajorOccurences("Business"));
        pieChartDataset.setValue("HDFS", countMajorOccurences("HDFS"));
        pieChartDataset.setValue("Nursing", countMajorOccurences("Nursing"));
        
        JFreeChart pieChart = ChartFactory.createPieChart("Student Majors", pieChartDataset, true, true, Locale.US);
        
        pieChartPanel = new ChartPanel(pieChart);
        pieChartPanel.setPreferredSize(new Dimension(450,100));
        
        this.jPanel2 = myGUI.studentCharts.jPanel2;
        jPanel2.setLayout(new BorderLayout());
        jPanel2.add(pieChartPanel, BorderLayout.WEST);
        jPanel2.validate();
        
//        // add the chart to a frame to be displayed to the user
//        pieChartFrame = new ChartFrame("Degree Status", pieChart, true);
//        pieChartFrame.setVisible(true);
//        pieChartFrame.setSize(750, 500);
    }

    private int countMajorOccurences(String major) {
        int result = 0;
        // counts the occurences of the degree status
        for (StudentRecord studentRecord : studentMenu.studentRecordData) {
            if (studentRecord.getMajor().equals(major)) {
                result++;
            }
        }
        return result;
    }

    private int countDegreeStatusOccurences(String degreeStatus) {
        int result = 0;
        // counts the occurences of the major
        for (StudentRecord studentRecord : studentMenu.studentRecordData) {
            if (studentRecord.getDegreeStatus().equals(degreeStatus)) {
                result++;
            }
        }
        return result;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
